[build]
  base = "client/"
  publish = "dist/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://api.travel-health.com"
  VITE_SOCKET_URL = "wss://api.travel-health.com"
  VITE_ENVIRONMENT = "production"

[context.staging.environment]
  VITE_API_URL = "https://staging-api.travel-health.com"
  VITE_SOCKET_URL = "wss://staging-api.travel-health.com"
  VITE_ENVIRONMENT = "staging"

[context.development.environment]
  VITE_API_URL = "http://localhost:5000"
  VITE_SOCKET_URL = "ws://localhost:5000"
  VITE_ENVIRONMENT = "development"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' *.travel-health.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' *.travel-health.com ws: wss:;"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
