services:
  - type: web
    name: travel-health-api
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRY
        value: 24h
      - key: CORS_ORIGIN
        value: https://adlords.netlify.app
      - key: REDIS_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: SENTRY_DSN
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

  - type: redis
    name: travel-health-cache
    ipAllowList: []
    plan: free