services:
  - type: web
    name: adlords-api
    env: node
    buildCommand: cd server && npm install --production=false && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRY
        value: 24h
      - key: CORS_ORIGIN
        value: https://adlords.netlify.app
